# Using Compose (key feature: to have multiple isolated environments on a single host) is essentially a three-step process:
# 1.Define your app's environment with a Dockerfile so it can be reproduced anywhere.
# 2.Define the services that make up your app in a compose.yaml file so they can be run together in an isolated environment.
# 3.Run docker compose up and the Docker compose command starts and runs your entire app.

#Automated testing environments
#An important part of any Continuous Deployment or Continuous Integration process is the automated test suite. 
#Automated end-to-end testing requires an environment in which to run tests. Compose provides a convenient way to create and destroy 
#isolated testing environments for your test suite. By defining the full environment in a Compose file, 
#you can create and destroy these environments in just a few commands:
#$ docker compose up -d
#$ ./run_tests
#$ docker compose down

#CMD:
#docker compose up

version: '3.9'

services:
  
  wordpress:
    #image: wordpress:latest
    #container_name: wordpress-app
    build:
      context: ./requirements/wordpress
    restart: always
    expose:
      - "8080:8000"
    volumes:
      volumes:
      #- ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wordpress_data:/var/www/html
      - ./wordpress:/var/www/html
    env_file:
      - .env

    #environment:
      #WORDPRESS_DP_HOST: mariadb
      #WORDPRESS_DB_NAME: "${DB_NAME}"
      #WORDPRESS_DB_USER1: "${MYSQL_USER1}"
      #WORDPRESS_DB_PASSWORD1: "${MYSQL_PASSWORD1}"
      #WORDPRESS_DB_USER2: "${MYSQL_USER2}"
      #WORDPRESS_DB_PASSWORD2: "${MYSQL_PASSWORD2}"
      #VIRTUAL_HOST: example.commandLETSENCRYPT_HOST: example.com
    depends_on:
      - mysql
    links:
      - mysql  

  ngnix:
    #container_name: nginx
    #we pull the Nginx proxy Docker image
    #image: nginx:latest
    build:
      context: ./requirements/nginx
    restart: always
    #build: .
    #expose ports 80 and 443 to the host container which will be used to connect to the outer world
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - /wordpress_data/html:/var/www/html
      #created volumes for the Nginx HTML page
      - ./nginx/html:/usr/share/nginx/html
      #directory where all the SSL certificates will be stored
      - ./nginx/certs:/etc/nginx/certs
      #directory for Virtual hosts which is what we used above to add additional nginx configuration
      #- ./nginx/vhost:/etc/nginx/vhost.d
    links:
      - wordpress
    env_file:
      - .env 
    #logging:
      #option:
       #we have configured the file upload size for the WordPress and phpMyAdmin sites
        #max-size: "10m"
       #max-file: "3"

   # depends_on:
    #  - mariadb

  mariadb:
    #container_name: mariadb
    #image:
    build:
      context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

    


  volumes:
    data_db:
    data_wordpress:

  network:

  entrypoint:
