version: '3.3'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/wordpress
      o: bind
      type: volume
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/mariadb
      o: bind
      type: volume
networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    restart: always
    #build: .
    #expose ports 80 and 443 to the host container which will be used to connect to the outer world
    ports:
      - 443:443
    depends_on:
      - wordpress  
    volumes:
      #- ./nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
      #created volumes for the Nginx HTML page
      #- ./nginx/html:/usr/share/nginx/html
      #directory where all the SSL certificates will be stored
      #- ./nginx/certs:/etc/nginx/certs
      #directory for Virtual hosts which is what we used above to add additional nginx configuration
      #- ./nginx/vhost:/etc/nginx/vhost.d
    networks:
      - inception  
    #links:
      #- wordpress
    #env_file:
      #- .env
  wordpress:
    #image: wordpress:latest
    container_name: wordpress
    build: ./requirements/wordpress/.
      #context: ./requirements/wordpress
    restart: always
    expose:
      - "80"
    volumes:
      - /home/vgejno/data/wordpress_data:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      #- wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
      
  mariadb:
    container_name: mariadb
    #image:
    build: ./requirements/mariadb/.
      #context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
