version: '3'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/wordpress
      o: bind
      type: volume

  mariadb_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/mariadb
      o: bind
      type: volume

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/.
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress  
    volumes:
      - mariadb_data:/var/lib/mysql
      - wordpress_data:/var/www/html
    networks:
      - inception  
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
      
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
      #context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - wordpress_data:/var/www/html
    networks:
      - inception
