version: '3.3'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: ${HOST_VOLUME_ROOT}/wordpress
      o: bind
      type: volume

  mariadb_data:
    driver: local
    driver_opts:
      device: ${HOST_VOLUME_ROOT}/mariadb
      o: bind
      type: volume

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: inception_nginx
    build: ./requirements/nginx/.
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress  
    volumes:
      #- mariadb_data:/var/lib/mysql
      - wordpress_data:/var/www/html
    networks:
      - inception  
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: inception_wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    volumes:
      - wordpress_data:/var/www/html
      #- /home/vgejno/data/wordpress_data:/var/www/html
      #- ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
      
  mariadb:
    container_name: mariadb
    image: inception_mariadb
    build: ./requirements/mariadb
      #context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      # - wordpress_data:/var/www/html
    networks:
      - inception
