version: '3.9'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/wordpress
      o: bind
      type: none

  mariadb_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    # image: nginx
    build: requirements/nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress  
    networks:
      - inception  
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    # image: wordpress
    build: ./requirements/wordpress
      # context: ./requirements/wordpress
      # dockerfile: Dockerfile
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    ports:
      - 9000
    networks:
      - inception
    env_file:
      - .env
      
  mariadb:
    container_name: mariadb
    # image: mariadb
    build: ./requirements/mariadb
  #     #context: ./requirements/mariadb
    restart: always
    ports:
      - 3306:3306 
    volumes:
      - mariadb_data:/var/lib/mysql
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env