version: '3.9'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/wordpress
      o: bind
      type: none

  mariadb_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/mariadb
      o: bind
      type: none

networks:
  back:
  front:

services:
  nginx:
    container_name: nginx
    # image: nginx
    build:
      context: ./requirements/nginx
      args:
        NX_DOMAIN_NAME: ${DOMAIN_NAME}
        NX_USER_ADMIN_EMAIL: ${USER_ADMIN_EMAIL}
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress  
    networks:
      front:
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    # image: wordpress
    build:
      context: ./requirements/wordpress
      args:
        WP_DB_HOST: ${DB_HOST}
        WP_DB_NAME: ${DB_NAME}
        WP_DB_USER: ${DB_USER}
        WP_DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/wordpress
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
      - USER_ADMIN_EMAIL=${USER_ADMIN_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TITLE=${TITLE}
    depends_on:
      - mariadb
    networks:
      back:
      front:
    env_file:
      - .env
      
  mariadb:
    container_name: mariadb
    # image: mariadb
    build: ./requirements/mariadb
  #     #context: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      back:
        aliases:
          - mysql
    env_file:
      - .env
