version: '3.9'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/wordpress
      o: bind
      type: none

  mariadb_data:
    driver: local
    driver_opts:
      device: /home/vgejno/data/mariadb
      o: bind
      type: none

networks:
  back:
  front:

services:
  nginx:
    container_name: nginx
    # image: nginx
    build: requirements/nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress  
    networks:
      front:
    args:
      NX_DOMAIN_NAME: ${DOMAINE_NAME}
      NX_USER_ADMIN_EMAIL: ${USER_ADMIN_EMAIL}
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    # image: wordpress
    build: ./requirements/wordpress
      # context: ./requirements/wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      back:
      front:
    env_file:
      - .env
      
  mariadb:
    container_name: mariadb
    # image: mariadb
    build: ./requirements/mariadb
  #     #context: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      back:
        aliases:
          - mysql
    env_file:
      - .env
